# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'computerwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GREENWINDOW(object):
    def setupUi(self, GREENWINDOW):
        GREENWINDOW.setObjectName("GREENWINDOW")
        GREENWINDOW.resize(520, 800)
        GREENWINDOW.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(GREENWINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(20, 100, 480, 200))
        self.result.setStyleSheet("color: rgb(87, 227, 137);\n"
"\n"
"font: 40pt \"MS Shell Dlg 2\";\n"
"border-radius:20px;\n"
"")
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.ox2 = QtWidgets.QPushButton(self.centralwidget)
        self.ox2.setGeometry(QtCore.QRect(210, 300, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox2.sizePolicy().hasHeightForWidth())
        self.ox2.setSizePolicy(sizePolicy)
        self.ox2.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox2.setText("")
        self.ox2.setObjectName("ox2")
        self.ox6 = QtWidgets.QPushButton(self.centralwidget)
        self.ox6.setGeometry(QtCore.QRect(320, 410, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox6.sizePolicy().hasHeightForWidth())
        self.ox6.setSizePolicy(sizePolicy)
        self.ox6.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox6.setText("")
        self.ox6.setObjectName("ox6")
        self.name3 = QtWidgets.QLabel(self.centralwidget)
        self.name3.setGeometry(QtCore.QRect(100, 0, 300, 100))
        self.name3.setStyleSheet("font: 75 40pt \"Dyuthi\";\n"
"color: rgb(51, 209, 122);\n"
"font: 75 32pt \"MS Sans Serif\";\n"
"border-radius: 15px;")
        self.name3.setAlignment(QtCore.Qt.AlignCenter)
        self.name3.setWordWrap(False)
        self.name3.setObjectName("name3")
        self.turns = QtWidgets.QLabel(self.centralwidget)
        self.turns.setGeometry(QtCore.QRect(20, 140, 480, 90))
        self.turns.setStyleSheet("color: rgb(46, 194, 126);\n"
"border-radius:20px;\n"
"font: 32pt \"MS Shell Dlg 2\";\n"
"")
        self.turns.setText("")
        self.turns.setObjectName("turns")
        self.coback = QtWidgets.QPushButton(self.centralwidget)
        self.coback.setGeometry(QtCore.QRect(0, 690, 160, 40))
        self.coback.setStyleSheet("color: rgb(38, 162, 105);\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"")
        self.coback.setAutoDefault(False)
        self.coback.setObjectName("coback")
        self.ox3 = QtWidgets.QPushButton(self.centralwidget)
        self.ox3.setGeometry(QtCore.QRect(320, 300, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox3.sizePolicy().hasHeightForWidth())
        self.ox3.setSizePolicy(sizePolicy)
        self.ox3.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox3.setText("")
        self.ox3.setObjectName("ox3")
        self.ox5 = QtWidgets.QPushButton(self.centralwidget)
        self.ox5.setGeometry(QtCore.QRect(210, 410, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox5.sizePolicy().hasHeightForWidth())
        self.ox5.setSizePolicy(sizePolicy)
        self.ox5.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox5.setText("")
        self.ox5.setObjectName("ox5")
        self.cquit = QtWidgets.QPushButton(self.centralwidget)
        self.cquit.setGeometry(QtCore.QRect(350, 650, 220, 60))
        self.cquit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 162, 105);\n"
"font: 75 28pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.cquit.setAutoDefault(False)
        self.cquit.setObjectName("cquit")
        self.ox4 = QtWidgets.QPushButton(self.centralwidget)
        self.ox4.setGeometry(QtCore.QRect(100, 410, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox4.sizePolicy().hasHeightForWidth())
        self.ox4.setSizePolicy(sizePolicy)
        self.ox4.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox4.setText("")
        self.ox4.setObjectName("ox4")
        self.ox7 = QtWidgets.QPushButton(self.centralwidget)
        self.ox7.setGeometry(QtCore.QRect(100, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox7.sizePolicy().hasHeightForWidth())
        self.ox7.setSizePolicy(sizePolicy)
        self.ox7.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox7.setText("")
        self.ox7.setObjectName("ox7")
        self.ox9 = QtWidgets.QPushButton(self.centralwidget)
        self.ox9.setGeometry(QtCore.QRect(320, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox9.sizePolicy().hasHeightForWidth())
        self.ox9.setSizePolicy(sizePolicy)
        self.ox9.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox9.setText("")
        self.ox9.setObjectName("ox9")
        self.ox1 = QtWidgets.QPushButton(self.centralwidget)
        self.ox1.setGeometry(QtCore.QRect(100, 300, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox1.sizePolicy().hasHeightForWidth())
        self.ox1.setSizePolicy(sizePolicy)
        self.ox1.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox1.setText("")
        self.ox1.setObjectName("ox1")
        self.ox8 = QtWidgets.QPushButton(self.centralwidget)
        self.ox8.setGeometry(QtCore.QRect(210, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox8.sizePolicy().hasHeightForWidth())
        self.ox8.setSizePolicy(sizePolicy)
        self.ox8.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(51, 209, 122);\n"
"color: rgb(255, 255, 255);")
        self.ox8.setText("")
        self.ox8.setObjectName("ox8")
        self.cagain = QtWidgets.QPushButton(self.centralwidget)
        self.cagain.setGeometry(QtCore.QRect(-10, 650, 230, 60))
        self.cagain.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(38, 162, 105);\n"
"font: 75 26pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.cagain.setAutoDefault(False)
        self.cagain.setObjectName("cagain")
        GREENWINDOW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GREENWINDOW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 27))
        self.menubar.setObjectName("menubar")
        GREENWINDOW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GREENWINDOW)
        self.statusbar.setObjectName("statusbar")
        GREENWINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(GREENWINDOW)
        QtCore.QMetaObject.connectSlotsByName(GREENWINDOW)

    def retranslateUi(self, GREENWINDOW):
        _translate = QtCore.QCoreApplication.translate
        GREENWINDOW.setWindowTitle(_translate("GREENWINDOW", "MainWindow"))
        self.name3.setText(_translate("GREENWINDOW", "Tic-Tac-Toe"))
        self.coback.setText(_translate("GREENWINDOW", "Go back"))
        self.cquit.setText(_translate("GREENWINDOW", "    Quit ➩        "))
        self.cagain.setText(_translate("GREENWINDOW", "Play again"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GREENWINDOW = QtWidgets.QMainWindow()
    ui = Ui_GREENWINDOW()
    ui.setupUi(GREENWINDOW)
    GREENWINDOW.show()
    sys.exit(app.exec_())
