# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CHOICEWINDOW(object):
    def setupUi(self, CHOICEWINDOW):
        CHOICEWINDOW.setObjectName("CHOICEWINDOW")
        CHOICEWINDOW.resize(520, 800)
        CHOICEWINDOW.setStyleSheet("background-color: rgb(0,0,0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(CHOICEWINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.name1 = QtWidgets.QLabel(self.centralwidget)
        self.name1.setGeometry(QtCore.QRect(110, 20, 300, 100))
        self.name1.setStyleSheet("font: 75 32pt \"MS Sans Serif\";\n"
"color: rgb(53, 132, 228);\n"
"border-radius: 15px;")
        self.name1.setAlignment(QtCore.Qt.AlignCenter)
        self.name1.setWordWrap(False)
        self.name1.setObjectName("name1")
        self.pvpbut = QtWidgets.QPushButton(self.centralwidget)
        self.pvpbut.setGeometry(QtCore.QRect(-60, 220, 360, 80))
        self.pvpbut.setStyleSheet("color: rgb(237, 51, 59);\n"
"font: 75 32pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.pvpbut.setAutoDefault(False)
        self.pvpbut.setObjectName("pvpbut")
        self.compbut = QtWidgets.QPushButton(self.centralwidget)
        self.compbut.setGeometry(QtCore.QRect(210, 580, 360, 80))
        self.compbut.setStyleSheet("color: rgb(51, 209, 122);\n"
"font: 75 32pt \"MS Sans Serif\";\n"
"border-radius:15px;")
        self.compbut.setObjectName("compbut")
        self.playerbut = QtWidgets.QPushButton(self.centralwidget)
        self.playerbut.setEnabled(False)
        self.playerbut.setGeometry(QtCore.QRect(80, 400, 360, 80))
        self.playerbut.setStyleSheet("color: rgb(53, 132, 228);\n"
"font: 75 42pt \"Dyuthi\";\n"
"border-radius: 15px;\n"
"")
        self.playerbut.setObjectName("playerbut")
        self.vs1 = QtWidgets.QLabel(self.centralwidget)
        self.vs1.setGeometry(QtCore.QRect(130, 320, 90, 60))
        self.vs1.setStyleSheet("color:rgb(248, 228, 92);\n"
"font: 75 30pt \"Dyuthi\";\n"
"border-radius:5px;\n"
"")
        self.vs1.setAlignment(QtCore.Qt.AlignCenter)
        self.vs1.setObjectName("vs1")
        self.vs2 = QtWidgets.QLabel(self.centralwidget)
        self.vs2.setGeometry(QtCore.QRect(280, 500, 90, 60))
        self.vs2.setStyleSheet("color:rgb(248, 228, 92);\n"
"font: 75 30pt \"Dyuthi\";\n"
"border-radius:5px;\n"
"")
        self.vs2.setAlignment(QtCore.Qt.AlignCenter)
        self.vs2.setObjectName("vs2")
        self.quitall = QtWidgets.QPushButton(self.centralwidget)
        self.quitall.setGeometry(QtCore.QRect(-50, 670, 220, 60))
        self.quitall.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(53, 132, 228);\n"
"font: 75 28pt \"Dyuthi\";\n"
"border-radius: 15px;\n"
"")
        self.quitall.setAutoDefault(False)
        self.quitall.setObjectName("quitall")
        CHOICEWINDOW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CHOICEWINDOW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 27))
        self.menubar.setObjectName("menubar")
        CHOICEWINDOW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CHOICEWINDOW)
        self.statusbar.setObjectName("statusbar")
        CHOICEWINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(CHOICEWINDOW)
        QtCore.QMetaObject.connectSlotsByName(CHOICEWINDOW)

    def retranslateUi(self, CHOICEWINDOW):
        _translate = QtCore.QCoreApplication.translate
        CHOICEWINDOW.setWindowTitle(_translate("CHOICEWINDOW", "MainWindow"))
        self.name1.setText(_translate("CHOICEWINDOW", "Tic-Tac-Toe"))
        self.pvpbut.setText(_translate("CHOICEWINDOW", "Player  "))
        self.compbut.setText(_translate("CHOICEWINDOW", "Computer  "))
        self.playerbut.setText(_translate("CHOICEWINDOW", "Player"))
        self.vs1.setText(_translate("CHOICEWINDOW", "VS"))
        self.vs2.setText(_translate("CHOICEWINDOW", "VS"))
        self.quitall.setText(_translate("CHOICEWINDOW", "    Quit ➩ "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CHOICEWINDOW = QtWidgets.QMainWindow()
    ui = Ui_CHOICEWINDOW()
    ui.setupUi(CHOICEWINDOW)
    CHOICEWINDOW.show()
    sys.exit(app.exec_())
