# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_REDWINDOW(object):
    def setupUi(self, REDWINDOW):
        REDWINDOW.setObjectName("REDWINDOW")
        REDWINDOW.resize(520, 800)
        REDWINDOW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        REDWINDOW.setMouseTracking(True)
        REDWINDOW.setFocusPolicy(QtCore.Qt.NoFocus)
        REDWINDOW.setStyleSheet("background-color: rgb(0, 0, 0);")
        REDWINDOW.setProperty("tabletTracking", True)
        self.centralwidget = QtWidgets.QWidget(REDWINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.name2 = QtWidgets.QLabel(self.centralwidget)
        self.name2.setGeometry(QtCore.QRect(100, 0, 300, 100))
        self.name2.setStyleSheet("font: 75 32pt \"MS Sans Serif\";\n"
"\n"
"color: rgb(237, 51, 59);\n"
"\n"
"border-radius: 15px;")
        self.name2.setAlignment(QtCore.Qt.AlignCenter)
        self.name2.setWordWrap(False)
        self.name2.setObjectName("name2")
        self.backbut1 = QtWidgets.QPushButton(self.centralwidget)
        self.backbut1.setGeometry(QtCore.QRect(10, 710, 160, 40))
        self.backbut1.setStyleSheet("color: rgb(237, 51, 59);\n"
"font: 75 24pt \"MS Sans Serif\";\n"
"\n"
"border-radius: 15px;\n"
"")
        self.backbut1.setAutoDefault(False)
        self.backbut1.setObjectName("backbut1")
        self.againbut1 = QtWidgets.QPushButton(self.centralwidget)
        self.againbut1.setGeometry(QtCore.QRect(-40, 650, 230, 60))
        self.againbut1.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(224, 27, 36);\n"
"font: 75 22pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.againbut1.setAutoDefault(False)
        self.againbut1.setObjectName("againbut1")
        self.quitbut1 = QtWidgets.QPushButton(self.centralwidget)
        self.quitbut1.setGeometry(QtCore.QRect(350, 650, 220, 60))
        self.quitbut1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(224, 27, 36);\n"
"font: 75 24pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.quitbut1.setAutoDefault(False)
        self.quitbut1.setObjectName("quitbut1")
        self.xo5 = QtWidgets.QPushButton(self.centralwidget)
        self.xo5.setGeometry(QtCore.QRect(210, 410, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo5.sizePolicy().hasHeightForWidth())
        self.xo5.setSizePolicy(sizePolicy)
        self.xo5.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo5.setText("")
        self.xo5.setObjectName("xo5")
        self.xo6 = QtWidgets.QPushButton(self.centralwidget)
        self.xo6.setGeometry(QtCore.QRect(320, 410, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo6.sizePolicy().hasHeightForWidth())
        self.xo6.setSizePolicy(sizePolicy)
        self.xo6.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo6.setText("")
        self.xo6.setObjectName("xo6")
        self.xo4 = QtWidgets.QPushButton(self.centralwidget)
        self.xo4.setGeometry(QtCore.QRect(100, 410, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo4.sizePolicy().hasHeightForWidth())
        self.xo4.setSizePolicy(sizePolicy)
        self.xo4.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo4.setText("")
        self.xo4.setObjectName("xo4")
        self.xo8 = QtWidgets.QPushButton(self.centralwidget)
        self.xo8.setGeometry(QtCore.QRect(210, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo8.sizePolicy().hasHeightForWidth())
        self.xo8.setSizePolicy(sizePolicy)
        self.xo8.setStyleSheet("border-radius:20px;\n"
"font: 75 50pt \"Garuda\";font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo8.setText("")
        self.xo8.setObjectName("xo8")
        self.xo9 = QtWidgets.QPushButton(self.centralwidget)
        self.xo9.setGeometry(QtCore.QRect(320, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo9.sizePolicy().hasHeightForWidth())
        self.xo9.setSizePolicy(sizePolicy)
        self.xo9.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo9.setText("")
        self.xo9.setObjectName("xo9")
        self.xo7 = QtWidgets.QPushButton(self.centralwidget)
        self.xo7.setGeometry(QtCore.QRect(100, 520, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo7.sizePolicy().hasHeightForWidth())
        self.xo7.setSizePolicy(sizePolicy)
        self.xo7.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo7.setText("")
        self.xo7.setObjectName("xo7")
        self.gobackabove = QtWidgets.QPushButton(self.centralwidget)
        self.gobackabove.setGeometry(QtCore.QRect(10, 710, 160, 40))
        self.gobackabove.setStyleSheet("color: rgb(237, 51, 59);\n"
"font: 75 24pt \"MS Sans Serif\";\n"
"\n"
"border-radius: 15px;\n"
"")
        self.gobackabove.setAutoDefault(False)
        self.gobackabove.setObjectName("gobackabove")
        self.hardbut = QtWidgets.QPushButton(self.centralwidget)
        self.hardbut.setGeometry(QtCore.QRect(280, 530, 240, 80))
        self.hardbut.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(224, 27, 36);\n"
"font: 75 32pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.hardbut.setAutoDefault(False)
        self.hardbut.setObjectName("hardbut")
        self.res12 = QtWidgets.QLabel(self.centralwidget)
        self.res12.setGeometry(QtCore.QRect(20, 100, 480, 200))
        self.res12.setStyleSheet("color: rgb(87, 227, 137);\n"
"\n"
"font: 40pt \"MS Shell Dlg 2\";\n"
"border-radius:20px;\n"
"")
        self.res12.setText("")
        self.res12.setAlignment(QtCore.Qt.AlignCenter)
        self.res12.setObjectName("res12")
        self.mediumbut = QtWidgets.QPushButton(self.centralwidget)
        self.mediumbut.setGeometry(QtCore.QRect(140, 400, 240, 80))
        self.mediumbut.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(53, 132, 228);\n"
"font: 75 32pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.mediumbut.setAutoDefault(False)
        self.mediumbut.setObjectName("mediumbut")
        self.xo1 = QtWidgets.QPushButton(self.centralwidget)
        self.xo1.setGeometry(QtCore.QRect(100, 300, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo1.sizePolicy().hasHeightForWidth())
        self.xo1.setSizePolicy(sizePolicy)
        self.xo1.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo1.setText("")
        self.xo1.setObjectName("xo1")
        self.xo2 = QtWidgets.QPushButton(self.centralwidget)
        self.xo2.setGeometry(QtCore.QRect(210, 300, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo2.sizePolicy().hasHeightForWidth())
        self.xo2.setSizePolicy(sizePolicy)
        self.xo2.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo2.setText("")
        self.xo2.setObjectName("xo2")
        self.xo3 = QtWidgets.QPushButton(self.centralwidget)
        self.xo3.setGeometry(QtCore.QRect(320, 300, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xo3.sizePolicy().hasHeightForWidth())
        self.xo3.setSizePolicy(sizePolicy)
        self.xo3.setStyleSheet("border-radius:20px;\n"
"font: 75 40pt \"MS Sans Serif\";\n"
"background-color:rgb(224, 27, 36);\n"
"color: rgb(222, 221, 218);")
        self.xo3.setText("")
        self.xo3.setObjectName("xo3")
        self.easybut = QtWidgets.QPushButton(self.centralwidget)
        self.easybut.setGeometry(QtCore.QRect(10, 260, 240, 80))
        self.easybut.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(51, 209, 122);\n"
"font: 75 32pt \"MS Sans Serif\";\n"
"border-radius: 15px;\n"
"")
        self.easybut.setAutoDefault(False)
        self.easybut.setObjectName("easybut")
        self.turnshow = QtWidgets.QLabel(self.centralwidget)
        self.turnshow.setGeometry(QtCore.QRect(20, 150, 480, 80))
        self.turnshow.setStyleSheet("font: 75 34pt \"MS Sans Serif\";\n"
"\n"
"color:rgb(224, 27, 36);")
        self.turnshow.setText("")
        self.turnshow.setAlignment(QtCore.Qt.AlignCenter)
        self.turnshow.setObjectName("turnshow")
        REDWINDOW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(REDWINDOW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 27))
        self.menubar.setObjectName("menubar")
        REDWINDOW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(REDWINDOW)
        self.statusbar.setObjectName("statusbar")
        REDWINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(REDWINDOW)
        QtCore.QMetaObject.connectSlotsByName(REDWINDOW)

    def retranslateUi(self, REDWINDOW):
        _translate = QtCore.QCoreApplication.translate
        REDWINDOW.setWindowTitle(_translate("REDWINDOW", "MainWindow"))
        self.name2.setText(_translate("REDWINDOW", "Tic-Tac-Toe"))
        self.backbut1.setText(_translate("REDWINDOW", "Go back"))
        self.againbut1.setText(_translate("REDWINDOW", "   Play again"))
        self.quitbut1.setText(_translate("REDWINDOW", "    Quit ➩         "))
        self.gobackabove.setText(_translate("REDWINDOW", "Go back"))
        self.hardbut.setText(_translate("REDWINDOW", "Hard"))
        self.mediumbut.setText(_translate("REDWINDOW", "Medium"))
        self.easybut.setText(_translate("REDWINDOW", "Easy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    REDWINDOW = QtWidgets.QMainWindow()
    ui = Ui_REDWINDOW()
    ui.setupUi(REDWINDOW)
    REDWINDOW.show()
    sys.exit(app.exec_())
